### ISSUE TITLE
failed to connect to mongo from meteor app

### ISSUE THREAD

**Issue by QHose** [tozd/docker-meteor-mongodb#3]
hi,

I constantly get this error, no matter what I try
`MongoError: failed to connect to server [mongodb:27017] on first connect` 

my docker compose file
```
version: "3.3"
services:
  mongodb:
        image: tozd/mongodb:3.4
        container_name: "mongodb"
        volumes:
          - .\mongo\log:/var/log/mongod
          - .\mongo\data:/var/lib/mongodb
          - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/etc/service/mongod/
        ports:
            - 27017:27017
        networks:
        - integrationLAN
  qrs:
    image: qrsmeteor:1.0.0
    environment:
        - MONGO_URL=mongodb://meteor:testpassword@mongodb:27017/meteor
        - PORT=3000 
        - ROOT_URL=http://localhost
    volumes:
        - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/meteorQRS/config
    ports:
    -  "80:3000"
    links:
        - mongodb
    depends_on:
        - mongodb
    networks:
      - integrationLAN
networks:
  integrationLAN:
```

run.config
```
MONGODB_ADMIN_PWD='testpassword'
MONGODB_CREATE_PWD='testpassword'
MONGODB_OPLOGGER_PWD='testpassword'
```
my mounted config folder with the run.config in it:
![image](https://user-images.githubusercontent.com/12411165/27947368-d75fa7c6-62f5-11e7-9304-6439c815ecdf.png)

**Comment by mitar** [comment]
`tozd/mongodb` is a different Docker image than `tozd/meteor-mongodb`.

**Comment by QHose** [comment]
thanks, I updated the image, still same issue. Also note I commented out the volume mapping so I constantly get a fresh mongo server, I only keep the volume to the run.config where we defined the users and passwords.

```
version: "3.3"
services:
  mongodb:
        image: **tozd/meteor-mongodb:2.6**
        container_name: "mongodb"
        volumes:
        #   - .\mongo\log:/var/log/mongod
        #   - .\mongo\data:/var/lib/mongodb
          - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/etc/service/mongod/
        ports:
            - 27017:27017
        networks:
        - integrationLAN
  qrs:
    image: qrsmeteor:1.0.0
    environment:
        - MONGO_URL=mongodb://meteor:testpassword@mongodb:27017/meteor
        # - MONGO_URL=mongodb://heroku_r1wrm527:kcedtl5po5bna0qbj2rouo8cau@ds145892.mlab.com:45892/heroku_r1wrm527
        # mongodb://username:password@127.0.0.1:27017/meteor
        - VIRTUAL_HOST=foo.bar.com
        - PORT=3000 
        - ROOT_URL=http://localhost
    volumes:
        - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/meteorQRS/config
    ports:
    -  "80:3000"
    links:
        - mongodb
    depends_on:
        - mongodb
    networks:
      - integrationLAN
networks:
  integrationLAN:
```

**Comment by mitar** [comment]
Config file has to be volume mounted into `/etc/service/mongod/run.config` and be named exactly like that. It does not seem you are doing that?

**Comment by QHose** [comment]
mmm, so I thought `run.config` was only a file. 
and I mapped just the folders...  But If I do something very stupid (in my view), I suddenly get a better error: `mongoError: auth failed'

`  - C:\Users\mbj\Documents\GitHub\qrsbuild\config\run.config:/etc/service/mongod/run.config`

**Comment by mitar** [comment]
Yes, you should volume mount a config file. Docker allows that as well. So you should mount only one file, config file, into that directory.

**Comment by QHose** [comment]
ah, I have multiplefiles there. will try in a different dir.

PS: I also tried to use the standard mongo image, it it works very fast with issues

```
version: "3.3"
services:
    # mongodb:
    #     image: tozd/meteor-mongodb:2.6
    #     container_name: "mongodb"
    #     volumes:
    #     #   - .\mongo\log:/var/log/mongod
    #     #   - .\mongo\data:/var/lib/mongodb
    #         - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/etc/service/mongod
    #     ports:
    #         - 27017:27017
    #     networks:
    #     - integrationLAN
    mongodb:
        image: mongo
        container_name: "mongodb"
        networks:
        - integrationLAN
    qrs:
        image: qrsmeteor:1.0.0
        environment:
            - MONGO_URL=mongodb://mongodb:27017/
            # - MONGO_URL=mongodb://meteor:testpassword@mongodb:27017/meteor
            # - MONGO_URL=mongodb://heroku_r1wrm527:kcedtl5po5bna0qbj2rouo8cau@ds145892.mlab.com:45892/heroku_r1wrm527
            # mongodb://username:password@127.0.0.1:27017/meteor
            - VIRTUAL_HOST=foo.bar.com
            - PORT=3000 
            - ROOT_URL=http://localhost
        volumes:
         - C:\Users\mbj\Documents\GitHub\qrsbuild\config:/meteorQRS/config
        ports:
        -  "80:3000"
        links:
        - mongodb
        depends_on:
        - mongodb
        networks:
        - integrationLAN
networks:
    integrationLAN:
```
